server:
  port: 5432
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres: // gxicaibdjnvizw : f64a10df017c1fd056d576edb7cf6cfb19ed4a3c574ca2b3528f7d952dc5646b @ ec2-34-195-143-54.compute-1.amazonaeok.com : 5432 / d4406av
    username: gxicaibdjnvizw
    password: f64a10df017c1fd056d576edb7cf6cfb19ed4a3c574ca2b3528f7d952dc5646b
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    renerate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o baootcamp DIO - Santander